"""Shared test fixtures for park_logs_service tests."""
from datetime import datetime


def make_log(
    id: int = 1,
    timestamp: datetime | None = None,
    in_count: int = 5,
    out_count: int = 3,
    net_flow: int = 2,
    current_vehicles: int = 50,
    parking_percentage: float | None = 22.52,
    api_temperature: float | None = 28.0,
    api_humidity: float | None = 60.0,
    api_feels_like: float | None = 30.0,
    api_clouds: float | None = 20.0,
    board_temperature: float | None = 35.0,
    is_raining: bool = False,
    pir_in_trigger: int = 1,
    pir_out_trigger: int = 0,
    raw_ultrasonic_in_us: float | None = None,
    ultrasonic_in_cm: float | None = None,
    raw_lidar_in_analog: float | None = None,
    raw_ultrasonic_out_us: float | None = None,
    ultrasonic_out_cm: float | None = None,
    raw_lidar_out_analog: float | None = None,
    lidar_in_cm: float | None = None,
    lidar_out_cm: float | None = None,
    direction_view: str = "IN",
    occupancy_change: float | None = None,
    sensor_gap_in: float | None = None,
    sensor_gap_out: float | None = None,
    in_out_ratio: float = 1.0,
) -> dict:
    if timestamp is None:
        timestamp = datetime(2026, 4, 14, 12, 0, 0)
    return {
        "id": id,
        "timestamp": timestamp,
        "in_count": in_count,
        "out_count": out_count,
        "net_flow": net_flow,
        "current_vehicles": current_vehicles,
        "parking_percentage": parking_percentage,
        "api_temperature": api_temperature,
        "api_humidity": api_humidity,
        "api_feels_like": api_feels_like,
        "api_clouds": api_clouds,
        "board_temperature": board_temperature,
        "is_raining": is_raining,
        "pir_in_trigger": pir_in_trigger,
        "pir_out_trigger": pir_out_trigger,
        "raw_ultrasonic_in_us": raw_ultrasonic_in_us,
        "ultrasonic_in_cm": ultrasonic_in_cm,
        "raw_lidar_in_analog": raw_lidar_in_analog,
        "raw_ultrasonic_out_us": raw_ultrasonic_out_us,
        "ultrasonic_out_cm": ultrasonic_out_cm,
        "raw_lidar_out_analog": raw_lidar_out_analog,
        "lidar_in_cm": lidar_in_cm,
        "lidar_out_cm": lidar_out_cm,
        "direction_view": direction_view,
        "occupancy_change": occupancy_change,
        "sensor_gap_in": sensor_gap_in,
        "sensor_gap_out": sensor_gap_out,
        "in_out_ratio": in_out_ratio,
    }
